import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
REPO=ROOT
TEMPLATE=r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ATLAS · 117 research missions</title>
<link rel="stylesheet" href="vendor/katex/katex.min.css"><script src="vendor/katex/katex.min.js"></script>
<style>
:root{color-scheme:light;--ink:#142338;--muted:#586b82;--blue:#225fc5;--line:#d8e0eb;--paper:#f6f8fc}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.6 system-ui,-apple-system,Segoe UI,sans-serif}a{color:var(--blue);overflow-wrap:anywhere}button,input,select{font:inherit}button{cursor:pointer}header{background:#101d32;color:white;padding:44px max(24px,calc((100vw - 1300px)/2));border-top:5px solid #8cbcff}header .eyebrow{color:#9bbcf0;font-size:13px;letter-spacing:.2em}header h1{font-size:clamp(34px,5vw,65px);line-height:1.1;max-width:1000px;margin:12px 0}header p{max-width:850px;color:#d4dfef;margin:18px 0 0}header a{color:#b7d4ff}.meta{display:flex;flex-wrap:wrap;gap:28px;margin-top:25px;color:#e1ebf9}.meta strong{display:block;font-size:25px;font-weight:550}.meta span{font-size:13px;color:#afc1d9}main{max-width:1350px;margin:auto;padding:30px 24px;display:grid;grid-template-columns:350px minmax(0,1fr);gap:35px}.filters{display:flex;gap:12px;flex-wrap:wrap}.filters label{display:block;font-size:13px;color:var(--muted);width:100%}.filters input,.filters select{width:100%;background:white;border:1px solid #b3c1d5;border-radius:5px;padding:10px;color:var(--ink)}#count{font-size:14px;margin:14px 0;color:var(--muted)}#list{display:grid;gap:8px;max-height:68vh;overflow-y:auto;padding:2px}aside{align-self:start}.project{padding:14px 16px;text-align:left;background:white;border:1px solid var(--line);border-radius:6px;line-height:1.35;width:100%;color:var(--ink)}.project .id{font-size:12px;color:var(--blue);font-weight:600}.project .name{display:block;font-size:16px;margin:5px 0}.project .original{display:block;font-size:13px;color:var(--muted)}.project[aria-current=true]{border-color:var(--blue);background:#eaf1fe;box-shadow:inset 3px 0 var(--blue)}article{min-width:0;background:white;padding:30px;border:1px solid var(--line);border-radius:8px;align-self:start}article{overflow-wrap:anywhere}.project{overflow-wrap:anywhere}.math-box{overflow-x:auto;padding:12px 4px;margin:12px 0}.katex-display{margin:.5em 0}
article h2{font-size:clamp(26px,3vw,38px);line-height:1.15;margin:10px 0}article h3{font-size:21px;margin:30px 0 10px}article h4{margin:20px 0 8px}.original-title{color:var(--muted)}.kicker{font-size:13px;color:var(--blue);font-weight:600;letter-spacing:.07em}.state{background:#edf3fb;padding:12px 16px;color:#3a5478;font-size:14px;border-radius:4px}.state a{font-size:inherit}.links{display:flex;gap:18px;flex-wrap:wrap;font-size:14px;margin:20px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f2f5fa;padding:14px 16px;border-radius:4px;font-size:14px;line-height:1.5}ul,ol{padding-left:22px}li{margin:8px 0}details{border-top:1px solid var(--line);padding:16px 0}summary{cursor:pointer;font-weight:550}summary:hover{color:var(--blue)}.flow{display:grid;gap:8px;margin:24px 0}.flow section{padding:13px 16px;background:#f3f6fb;border-left:3px solid #8cadda}.flow b{font-size:12px;color:var(--blue);letter-spacing:.06em;display:block}.flow p{font-size:14px;margin:5px 0}.flow .arrow{text-align:center;font-size:20px;color:var(--muted);line-height:1}.data{padding-left:16px;border-left:2px solid var(--line);margin:18px 0}.data p{font-size:14px;margin:7px 0}.visual-spec{font-size:14px;color:var(--muted)}.source-list li{font-size:14px}footer{color:var(--muted);font-size:13px;padding:24px;max-width:1350px;margin:auto;border-top:1px solid var(--line)}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible{outline:3px solid #ed9b19;outline-offset:3px}@media(max-width:900px){main{grid-template-columns:290px minmax(0,1fr);gap:20px}article{padding:22px}}@media(max-width:720px){main{display:block;padding:20px 16px}header{padding:30px 20px}article{margin-top:24px}#list{grid-template-columns:1fr 1fr;max-height:320px}.project{padding:12px}.meta{gap:20px}.filters{display:grid;grid-template-columns:1fr 1fr}}@media(max-width:440px){#list,.filters{grid-template-columns:1fr}article{padding:18px}}@media print{header{background:white;color:black;padding:0}.eyebrow,.meta,aside,.links,footer{display:none}header p{color:black}header h1{font-size:26px}main{display:block;padding:0}article{border:0;padding:0}details{display:block}details>*{display:block!important}pre{break-inside:avoid}}
</style></head><body>
<header><div class="eyebrow">ATLAS RESEARCH PORTFOLIO · 2026</div><h1>117 ideas.<br>A universe of research.</h1><p>Applied Terrestrial &amp; Lunar/Astrophysical Studies. Every original project retained, with mission-inspired identities, governing models, data contracts, scientific resources and plans for independent validation.</p><div class="meta"><div><strong>117</strong><span>listed projects</span></div><div><strong>9</strong><span>session collections</span></div><div><strong id="source-total">—</strong><span>unique source links</span></div><div><strong>2</strong><span>retained D03 work packages</span></div></div></header>
<main><aside aria-label="Research project navigator"><div class="filters"><label>Find a project<input id="search" type="search" placeholder="Title, mission, model or topic"></label><label>Collection<select id="session"><option value="">All nine sessions</option></select></label></div><p id="count" aria-live="polite"></p><div id="list"></div></aside><article id="detail" aria-live="polite"></article></main>
<footer>Research proposal portfolio. NASA-inspired names do not imply NASA endorsement. Conceptual diagrams show proposed analysis paths; mathematical examples and observational data carry separate evidence labels. Source discovery reviewed 2026-10-02. Original concepts remain attributed through their unchanged titles and the <a href="https://spacegrant.arizona.edu/sites/spacegrant.arizona.edu/files/AZSGC%20Symposium%20Booklet%202021_website.pdf">2021 Arizona Space Grant program</a>.</footer>
<script id="catalog" type="application/json">__CATALOG__</script>
<script>
'use strict';
const projects=JSON.parse(document.getElementById('catalog').textContent), sessions=__SESSIONS__;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const list=v=>Array.isArray(v)?v:(v==null?[]:[v]);
const bullets=v=>'<ul>'+list(v).map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>';
const link=(url,title)=>'<a href="'+esc(url)+'" target="_blank" rel="noopener">'+esc(title)+'</a>';
const search=document.getElementById('search'), session=document.getElementById('session'), listEl=document.getElementById('list'), detail=document.getElementById('detail');
Object.entries(sessions).forEach(([k,v])=>{const o=document.createElement('option');o.value=k;o.textContent=k+' · '+v;session.append(o)});
document.getElementById('source-total').textContent=new Set(projects.flatMap(p=>p.sources.map(s=>s.url))).size;
let current=projects.some(p=>p.id===location.hash.slice(1))?location.hash.slice(1):'A01';
function renderList(){const q=search.value.toLowerCase().trim();const filtered=projects.filter(p=>(!session.value||p.session===session.value)&&(!q||JSON.stringify(p).toLowerCase().includes(q)));document.getElementById('count').textContent=filtered.length+' of 117 projects';listEl.replaceChildren();filtered.forEach(p=>{const b=document.createElement('button');b.className='project';b.type='button';b.setAttribute('aria-current',p.id===current?'true':'false');b.innerHTML='<span class="id">'+esc(p.id)+' · SESSION '+esc(p.session)+'</span><span class="name">'+esc(p.name)+'</span><span class="original">'+esc(p.original_title)+'</span>';b.addEventListener('click',()=>{select(p.id);detail.scrollIntoView({behavior:'smooth',block:'start'})});listEl.append(b)});if(!filtered.length)listEl.innerHTML='<p>No matching projects. Try a broader term.</p>'}
function select(id){current=id;history.replaceState(null,'','#'+id);renderList();renderDetail()}
function renderDetail(){const p=projects.find(x=>x.id===current),m=p.model;document.title=p.id+' · '+p.name+' · ATLAS';
const flow=[['QUESTION',p.question],['OBSERVABLES',p.data[0].fields],['MODEL',list(m.equations)[0]],['VALIDATION',list(p.validation)[0]]].map(([k,v])=>'<section><b>'+k+'</b><p>'+esc(v)+'</p></section>').join('<div class="arrow" aria-hidden="true">↓</div>');
detail.innerHTML='<div class="kicker">'+esc(p.id)+' · SESSION '+esc(p.session)+' / '+esc(sessions[p.session])+'</div><h2>'+esc(p.name)+'</h2><p class="original-title"><b>Original project</b><br>'+esc(p.original_title)+'</p><p class="state">Proposed research design. Models and data requirements are specified; project experiments and mission qualification remain to be performed.</p><div class="links">'+link('../projects/'+p.session+'/'+p.id+'.md','Open Markdown dossier')+link('../visuals/projects/'+p.id+'.svg','Open conceptual figure')+link('../docs/MODEL_ASSURANCE.md','Model assurance')+'</div><p>'+esc(p.summary)+'</p><h3>Scientific question</h3><p>'+esc(p.question)+'</p><h3>Testable hypothesis</h3><p>'+esc(p.hypothesis)+'</p><div class="flow" aria-label="Conceptual model dependency diagram">'+flow+'</div><p class="visual-spec">Conceptual analysis map. '+esc(p.visual.description||'')+'</p><h3>Governing model</h3>'+list(m.equations).map(e=>'<div class="math-box" data-equation="'+esc(e)+'"><pre>'+esc(e)+'</pre></div>').join('')+'<h4>Variables and units</h4>'+bullets(m.variables)+'<h4>Assumptions</h4>'+bullets(m.assumptions)+'<h4>Inference or simulation</h4><p>'+esc(m.method)+'</p><h4>Model limits</h4><p>'+esc(m.limitations)+'</p><details open><summary>Data and provenance contracts</summary>'+p.data.map(d=>'<div class="data"><h4>'+link(d.url,d.source)+'</h4>'+Object.entries(d).filter(([k])=>!['url','source'].includes(k)).map(([k,v])=>'<p><b>'+esc(k.replaceAll('_',' '))+':</b> '+esc(typeof v==='object'?JSON.stringify(v):v)+'</p>').join('')+'</div>').join('')+'</details><details open><summary>Staged execution</summary><ol>'+list(p.plan).map(x=>'<li>'+esc(x)+'</li>').join('')+'</ol></details><details open><summary>Verification and validation</summary>'+bullets(p.validation)+'<p class="visual-spec">Numerical gates are proposed requirements unless explicitly sourced. Freeze confirmatory gates before data collection.</p></details><details><summary>Resources and deliverables</summary>'+bullets(p.resources)+bullets(p.deliverables)+'</details><details><summary>Risks and interpretation</summary>'+bullets(p.risks)+'</details>'+(p.subprojects?'<details open><summary>Both retained research work packages</summary><pre>'+esc(JSON.stringify(p.subprojects,null,2))+'</pre></details>':'')+'<h3>Cited scientific resources</h3><ul class="source-list">'+p.sources.map(s=>'<li>'+link(s.url,s.title)+'<br>'+esc(s.support||'Model or data context.')+'</li>').join('')+'</ul>';
detail.querySelectorAll('[data-equation]').forEach(el=>{const e=el.dataset.equation;if(e.includes(String.fromCharCode(92))&&window.katex){try{katex.render(e,el,{displayMode:true,throwOnError:true,trust:false,strict:'warn',output:'htmlAndMathml'})}catch{el.setAttribute('data-math-fallback','true')}}});
}
search.addEventListener('input',renderList);session.addEventListener('change',renderList);window.addEventListener('hashchange',()=>{if(projects.some(p=>p.id===location.hash.slice(1)))select(location.hash.slice(1))});renderList();renderDetail();
</script></body></html>'''
def render():
    ps=json.loads((REPO/'catalog/projects.json').read_text(encoding='utf-8'))
    S=json.loads((REPO/'catalog/sessions.json').read_text(encoding='utf-8'))
    html=TEMPLATE.replace('__CATALOG__',json.dumps(ps,ensure_ascii=False).replace('<',chr(92)+'u003c')).replace('__SESSIONS__',json.dumps(S))
    (REPO/'web/atlas.html').write_text(html,encoding='utf-8')
    print('Explorer written:',len(html),'characters')
if __name__=='__main__':render()
